language: ruby
rvm:
  - 2.7.6

before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database blog_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test

script: bundle exec rspec spec
