language: ruby
rvm:
  - 1.9.3

before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database blog_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

script: bundle exec rspec spec
